[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Add this line to fix the "program size greater than maximum" error
board_build.partitions = huge_app.csv

monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit INA219 @ ^1.2.3